version: '3.8'

services:
  # Database
  db:
    image: mysql:8.0
    container_name: coffee_db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Services
  login_service:
    build:
      context: .
      dockerfile: ./services/login_service/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto
    

  adminlogin:
    build:
      context: .
      dockerfile: ./services/adminlogin/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "50011:50011"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto


  order_service:
    build:
      context: .
      dockerfile: ./services/order_service/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "5002:5002"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto

  analytics_service:
    build:
      context: .
      dockerfile: ./services/analytics_service/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "5003:5003"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto

  cafe_service:
    build: 
      context: .
      dockerfile: ./services/cafe_service/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "5004:5004"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto

  menu_service:
    build:
      context: .
      dockerfile: ./services/menu_service/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "5005:5005"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto

  inventory_service:
    build:
      context: .
      dockerfile: ./services/inventory_service/Dockerfile
    volumes:
     - ./shared_proto:/app/shared_proto
     - ./database:/app/database
    ports:
      - "5006:5006"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/shared_proto

  # Gateway
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - login_service
      - adminlogin
      - menu_service
      - inventory_service
      - cafe_service
      - order_service
      - analytics_service
    env_file:
      - .env
    volumes:
      - ./shared_proto:/app/shared_proto
      - ./database:/app/database
    environment:
      - PYTHONPATH=/app/shared_proto

  # Frontend
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - gateway

volumes:
  db_data:
